Repository QuakeMigrate/QuakeMigrate, pull requests merged in 2020-12, with the labels that each got.

#104 FEAT: Make trigger summary plotting optional
  examples/Icequake_Iceland/iceland_trigger.py
  examples/Icequake_Iceland/icequakes_iceland.ipynb
  examples/Icequake_Rutford/icequakes_rutford.ipynb
  examples/Icequake_Rutford/rutford_trigger.py
  examples/Volcanotectonic_Iceland/dike_intrusion_trigger.py
  examples/template_scripts/trigger.py
  quakemigrate/plot/trigger.py
  quakemigrate/signal/trigger.py
Labels: enhancement

#113 [FIX]: Amplitudes fixes
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.event
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.m
  examples/benchmarks/Volcanotectonic_Iceland/20140824000944240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000944240.m
  quakemigrate/io/cut_waveforms.py
  quakemigrate/io/data.py
  quakemigrate/signal/local_mag/amplitude.py
  quakemigrate/signal/scan.py
Labels: bug

#114 [FIX]: Fix resampling/upsampling bug; more explicit handling of data timing.
  quakemigrate/io/data.py
  quakemigrate/signal/onsets/stalta.py
  quakemigrate/util.py
Labels: bug, enhancement

#115 [FEAT]: Set value of STA/LTA onset in taper regions to 0
  examples/benchmarks/Icequake_Iceland/20140629184210336.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.event
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.event
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.event
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.picks
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.picks
  quakemigrate/signal/onsets/stalta.py
  quakemigrate/signal/pickers/gaussian.py
Labels: enhancement

#117 [FEAT]: Improvements to noise measurement in local mags sub-module
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000944240.amps
  quakemigrate/export/to_obspy.py
  quakemigrate/io/amplitudes.py
  quakemigrate/plot/amplitudes.py
  quakemigrate/signal/local_mag/amplitude.py
  quakemigrate/signal/local_mag/magnitude.py
Labels: enhancement

#118 [FEAT]: Output real waveforms
  examples/Volcanotectonic_Iceland/dike_intrusion_locate.py
  examples/benchmarks/Volcanotectonic_Iceland/20140824000109120.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000120180.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000128200.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000153880.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000233420.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000253360.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000301980.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000321640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000328780.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000354040.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000426380.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000443240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000451240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000458460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000512940.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000525640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000547720.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000612280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000616600.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000634320.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000703640.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000728280.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000735760.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000811460.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000907000.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000944240.amps
  examples/benchmarks/Volcanotectonic_Iceland/20140824000944240.event
  examples/template_scripts/locate.py
  quakemigrate/export/to_obspy.py
  quakemigrate/io/cut_waveforms.py
  quakemigrate/io/data.py
  quakemigrate/signal/local_mag/amplitude.py
  quakemigrate/signal/local_mag/magnitude.py
  quakemigrate/signal/scan.py
  tests/test_benchmarks.py
Labels: enhancement
